services:
  # Laravel PHP App
  backend:
    build:
      context: ./backend
    container_name: laravel
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
    command: >
      sh -c "
      until nc -z mysql 3306; do
        echo 'Waiting for MySQL...';
        sleep 3;
      done;
      php artisan migrate --force;
      php artisan serve --host=0.0.0.0 --port=8000
      "

  # React App
  frontend:
    build:
      context: ./frontend
    container_name: react
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    working_dir: /app
    stdin_open: true
    tty: true
    command: npm run dev -- --host

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    depends_on:
      - mysql

volumes:
  mysql_data:
